version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
            dockerfile: Dockerfile.build
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.build
        ports:
            - "80:80"
    postgres:
        build:
            context: ./database
            dockerfile: Dockerfile.test
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5432:5432'
