version: "3.8"
services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.build
        ports:
            - "80:80"
    postgres:
        build:
            context: ./database/postgresql
            dockerfile: Dockerfile.build
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5432:5432'
    nodeserver:
        build:
            context: ./app
            dockerfile: Dockerfile.build
        ports:
            - "3000:3000"
        depends_on:
            - postgres
